from typing_extensions import Protocol, runtime_checkable


@runtime_checkable
class BaseNetworkStream(Protocol):
    def read(self, max_bytes: int, timeout: float | None = None) -> bytes: ...
    def write_all(self, data: bytes, timeout: float | None = None) -> int: ...
    def close(self) -> None: ...


@runtime_checkable
class AsyncBaseNetworkStream(Protocol):
    async def read(self, max_bytes: int, timeout: float | None = None) -> bytes: ...
    async def write_all(self, data: bytes, timeout: float | None = None) -> int: ...
    async def close(self) -> None: ...
